### ISSUE TITLE
Error: INTERNAL Error: Decimal has a width of 255 which is bigger than the maximum supported width of 38

### ISSUE THREAD

**Issue by wonb168** [duckdblabs/postgres_scanner#26] opened 2022-10-04 13:09 UTC
when attach my gp, raise this error:
Error: INTERNAL Error: Decimal has a width of 255 which is bigger than the maximum supported width of 38
because of gp table have numeric column?
and how to solve this?

**Comment by hannes** [comment] 2022-11-09 16:03
Duplicate of #16 I think

**Closed by hannes** 2022-11-09 16:03 UTC
